# Official docker compose image.
image:
  name: docker/compose:latest

services:
  - docker:dind

before_script:
  - chmod +x ./setup_env.sh
  - ./setup_env.sh
  - cp .env web/.env
  - docker version
  - docker-compose version

build_backend:
  stage: build
  script:
    - docker-compose build
    - docker-compose up -d
build_frontend:
  stage: build
  script:
    - cd web
    - yarn
    - yarn build
    - ls
    - mv dist /var/www/new