version: '3'

services:
  rust:
    build: "api/."
    container_name: "rust"
    env_file:
      - .env
    ports:
      - '3000:3000'

  python:
    build: data/.
    container_name: "python"
    depends_on:
      - db
    env_file:
      - .env
  
  db:
    build: "db/."
    container_name: "db"
    env_file:
      - .env
    volumes:
      - ./data/volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
