version: '3'

services:
  python:
    build: .
    container_name: "python"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
      - HEADLESS=true
  
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    ports:
      - "4444:4444"
  
  db:
    image: "postgres:latest"
    container_name: "db"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    # volumes:
      # - ./volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'