version: '3'

services:
  db:
    image: "postgres:latest"
    container_name: "db"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    volumes:
      - ./volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'