version: '3'

services:
  python:
    build: data/.
    container_name: "python"
    depends_on:
      - db
    env_file:
      - .env
  
  db:
    image: "postgres:latest"
    container_name: "db"
    env_file:
      - .env
    volumes:
      - ./data/volume:/var/lib/postgresql/data
      #- ./data/views.sql:/docker-entrypoint-initdb.d/views.sql
    ports:
      - '5432:5432'