version: '3'

services:
  rust:
    build: "api/."
    container_name: "rust"
    env_file:
      - .env
    ports:
      - '8000:8000'
    #volumes:
      #- ./api/fullchain.pem:/app/fullchain.pem
      #- ./api/privkey.pem:/app/privkey.pem

  python:
    build: data/.
    container_name: "python"
    depends_on:
      - db
    env_file:
      - .env
  
  db:
    image: "postgres:latest"
    container_name: "db"
    env_file:
      - .env
    # volumes:
      # - ./data/volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
