version: '3'

services:
  web:
    container_name: "dstweb"
    build: "web/."
    restart: always
    ports:
      - "85:80"
  
  fetcher:
    container_name: "fetcher"
    environment: 
      - USER=root
      - PASSWORD=password
      - DBNAME=dststats
      - DBPORT=5432
      - TOKEN=<YOUR TOKEN HERE>
    build: 
      context: backend
      dockerfile: "fetcher/Dockerfile"

  server:
    container_name: "dstserver"
    build: 
      context: backend
      dockerfile: "api/Dockerfile"
    restart: always
    ports: 
      - "3000:3000"
    environment: 
      - USER=root
      - PASSWORD=password
      - DBNAME=dststats
      - DBPORT=5432
    

  db:
    container_name: "postgres"
    image: "postgres:latest"
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dststats
    volumes:
      - dst-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes: 
  dst-data:

#network:
  #main
    #external: true