version: '3'

services:
  web:
    container_name: "web"
    build: "web/."
    restart: always
    ports:
      - "127.0.0.1:83:80"

  fetcher:
    container_name: "fetcher"
    restart: always
    environment:
      - DBUSER=${DBUSER:-root}
      - DBPASSWORD=${DBPASSWORD:-password}
      - DBHOST=${DBHOST:-dstpostgres}
      - DBNAME=${DBNAME:-dststats}
      - DBPORT=${DBPORT:-5432}
      - TOKEN=${DST:-sample-token}
      # Alerting is done via messages to a discord channel
      - DISCORD_WEBHOOK_URL=$DISCORD_WEBHOOK_URL
    build:
      context: backend
      dockerfile: "fetch/Dockerfile"

  api:
    container_name: "api"
    build: 
      context: backend
      dockerfile: "api/Dockerfile"
    restart: always
    ports: 
      - "127.0.0.1:8003:8003"
    environment:
      - DBUSER=${DBUSER:-root}
      - DBPASSWORD=${DBPASSWORD:-password}
      - DBHOST=${DBHOST:-dstpostgres}
      - DBNAME=${DBNAME:-dststats}
      - DBPORT=${DBPORT:-5432}

  dstpostgres:
    container_name: "dstpostgres"
    image: "postgres:latest"
    restart: always
    environment:
      - POSTGRES_USER=${DBUSER:-root}
      - POSTGRES_PASSWORD=${DBPASSWORD:-password}
      - POSTGRES_DB=${DBNAME:-dststats}
    volumes:
      - dst-data:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'

volumes: 
  dst-data: