version: '3'

services:
  web:
    container_name: "dstweb"
    build: "web/."
    restart: always
    ports:
      - "127.0.0.1:83:80"
    #networks:
    #  - main

  fetcher:
    container_name: "dstfetcher"
    restart: always
    environment: 
      - USER=root
      - PASSWORD=password
      - DBNAME=dststats
      - DBPORT=5432
      - TOKEN=<YOUR TOKEN HERE>
    build: 
      context: backend
      dockerfile: "fetch/Dockerfile"
    #networks:
    #  - main

  server:
    container_name: "dstserver"
    build: 
      context: backend
      dockerfile: "api/Dockerfile"
    restart: always
    ports: 
      - "127.0.0.1:8003:8003"
    environment: 
      - USER=root
      - PASSWORD=password
      - DBNAME=dststats
      - DBPORT=5432
    #networks:
    #  - main

  # docker run --rm --name postgres_tmp --network="host" -p 5432:5432 -e POSTGRES_USER=root -e POSTGRES_PASSWORD=password -e POSTGRES_DB=mydatabase postgres
  db:
    container_name: "dstpostgres"
    image: "postgres:latest"
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dststats
    volumes:
      - dst-data:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'
    #networks:
    #  - main

  # docker run --rm --name redis_tmp --network="host" redis
  redis:
    container_name: "dstcache"
    image: "redis:latest"
    restart: always
    command: redis-server --requirepass redispassword
    ports:
      - "127.0.0.1:6379:6379"
    #networks:
    # - main

volumes: 
  dst-data:

#networks:
  #main:
    #external: true
