#!/bin/sh

echo TOKEN=$TOKEN >> .env
echo POSTGRES_USER=$POSTGRES_USER  >> .env
echo POSTGRES_PASSWORD=$POSTGRES_PASSWORD >> .env
echo POSTGRES_MULTIPLE_DATABASES=$POSTGRES_MULTIPLE_DATABASES >> .env
echo DB_SHORT=$DB_SHORT >> .env
echo DB_LONG=$DB_LONG >> .env
echo DB_HOST=$DB_HOST >> .env
echo ROCKET_ENV=$ROCKET_ENV >> .env
echo ROCKET_DATABASES=$ROCKET_DATABASES >> .env
echo VUE_APP_ENDPOINT=$VUE_APP_ENDPOINT >> .env