[global.databases]
shortterm = { url = "postgres://root:password@localhost:5432/shortterm" }
longterm = { url = "postgres://root:password@localhost:5432/longterm" }

[development]
address = "localhost"
log = "normal"
port = 3000

[staging]
address = "0.0.0.0"
log = "normal"
port = 3000

[production]
address = "0.0.0.0"
log = "normal"
port = 3000
