name: Build images

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        env:
          USER: ${{ github.actor }}
          TOKEN: ${{ github.token }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: USER,TOKEN
          script: |
            git clone git@github.com:ResamVi/dontstarve-datavis.git repo
            cd repo
            docker-compose build
            cd ..
            rm -rf repo