name: Deploy image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      env:
        DST: ${{ secrets.DST }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        envs: DST
        script: |
          git clone git@github.com:ResamVi/dontstarve-datavis.git repo
          docker-compose -p dontstarve -f repo/docker-compose.yml up --detach --build --force-recreate
          rm -rf repo